-- MySQL Script generated by MySQL Workbench
-- jue 18 feb 2016 09:03:28 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TIENDAONLINE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TIENDAONLINE` ;

-- -----------------------------------------------------
-- Schema TIENDAONLINE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TIENDAONLINE` DEFAULT CHARACTER SET utf8 ;
USE `TIENDAONLINE` ;

-- -----------------------------------------------------
-- Table `TIENDAONLINE`.`PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIENDAONLINE`.`PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `TIENDAONLINE`.`PRODUCTOS` (
  `ID_PRODUCTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PRODUCTO` VARCHAR(45) NOT NULL,
  `DESCRIPCCION_PRODUCTO` VARCHAR(500) NULL,
  `CATEGORIA_PRODUCTO` VARCHAR(45) NULL COMMENT 'Tabla de la lsita de productos de la tienda.',
  `PRECIO_PRODUCTO` VARCHAR(45) NULL,
  `DESCUENTO` DOUBLE NULL,
  `STOCK` INT NULL,
  `FOTO` VARCHAR(60) NULL,
  PRIMARY KEY (`ID_PRODUCTO`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProducto_UNIQUE` ON `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO` ASC);


-- -----------------------------------------------------
-- Table `TIENDAONLINE`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIENDAONLINE`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `TIENDAONLINE`.`USUARIOS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `CIUDAD` VARCHAR(45) NULL,
  `PROVINCIA` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `PAIS` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `ULTIMA_CONEC` DATE NULL,
  `NIVEL_PRIVILEGIO` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TIENDAONLINE`.`COMPRAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIENDAONLINE`.`COMPRAS` ;

CREATE TABLE IF NOT EXISTS `TIENDAONLINE`.`COMPRAS` (
  `ID_COMPRA` BIGINT NOT NULL AUTO_INCREMENT,
  `COMENTARIO_COMPRA` VARCHAR(45) NULL,
  `FK_ID_CLIENTE` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_COMPRA`),
  CONSTRAINT `fk_COMPRAS_CLIENTES`
    FOREIGN KEY (`FK_ID_CLIENTE`)
    REFERENCES `TIENDAONLINE`.`USUARIOS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_COMPRA_UNIQUE` ON `TIENDAONLINE`.`COMPRAS` (`ID_COMPRA` ASC);

CREATE INDEX `fk_COMPRAS_CLIENTES_idx` ON `TIENDAONLINE`.`COMPRAS` (`FK_ID_CLIENTE` ASC);


-- -----------------------------------------------------
-- Table `TIENDAONLINE`.`LINEAS_COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIENDAONLINE`.`LINEAS_COMPRA` ;

CREATE TABLE IF NOT EXISTS `TIENDAONLINE`.`LINEAS_COMPRA` (
  `CANTIDAD` INT NULL,
  `FK_ID_COMPRA` BIGINT NOT NULL,
  `FK_ID_PRODUCTO` INT NOT NULL,
  CONSTRAINT `fk_LINEAS_COMPRA_COMPRAS1`
    FOREIGN KEY (`FK_ID_COMPRA`)
    REFERENCES `TIENDAONLINE`.`COMPRAS` (`ID_COMPRA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LINEAS_COMPRA_PRODUCTOS1`
    FOREIGN KEY (`FK_ID_PRODUCTO`)
    REFERENCES `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_LINEAS_COMPRA_COMPRAS1_idx` ON `TIENDAONLINE`.`LINEAS_COMPRA` (`FK_ID_COMPRA` ASC);

CREATE INDEX `fk_LINEAS_COMPRA_PRODUCTOS1_idx` ON `TIENDAONLINE`.`LINEAS_COMPRA` (`FK_ID_PRODUCTO` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TIENDAONLINE`.`PRODUCTOS`
-- -----------------------------------------------------
START TRANSACTION;
USE `TIENDAONLINE`;
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (1, 'Ubuntu Wily Werewolf 15.10 Mens T-Shirt', 'The werewolf, also know as lycanthrope, is a mythological human with the ability to shapeshift into a wolf or a wolf-like creature, on a full moon, either purposely or after being placed under a curse or having been bitten by another.', 'vestible', '11.00', 0, 23, 'UBN11050-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (2, 'Ubuntu Pictogram Mens T-shirt', 'The new Ubuntu Pictogram T-shirt is a must have addition for any true Ubuntu enthusiast. With the pictogram design representing all things Ubuntu, make a statement, wear with pride, and be Ubuntu. Made from 100% cotton and neatly finished with the Ubuntu and Circle of Friends logo on the back of the shirt. ', 'vestible', '9.95', 0, 19, 'UBN11039-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (3, 'Ubuntu Vivid Vervet 15.04 Mens T-shirt', 'Native to Africa, the vervet monkey is known for its most human-like characteristics which makes it a perfect nonhuman primate model for understanding genetic and social behaviors of humans. The most significant studies done on vervet monkeys involve their communication and alarm calls, specifically in regard to kin and group recognition and particular predator sightings.', 'vestible', '11.00', 0, 36, 'UBN11047-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (4, 'Ubuntu Pictogram Ladies T-shirt', 'The new Ubuntu Pictogram T-shirt is a must have addition for any true Ubuntu enthusiast. With the pictogram design representing all things Ubuntu, make a statement, wear with pride, and be Ubuntu. Made from 100% cotton and neatly finished with the Ubuntu and Circle of Friends logo on the back of the shirt. ', 'vestible', '9.95', 0, 8, 'UBN12031-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (5, 'Ubuntu Infographic Ladies T-shirt', 'A statement t-shirt to add to your collection, representing Ubuntu at its very core! With the trademark COF logo embedded in the center and the fluid UbuntuTouch infographic, this t-shirt truly represents Ubuntu to the present day. Love Ubuntu, be Ubuntu, wear Ubuntu! Made from 100% cotton and finished with the Ubuntu and Circle of Friends logo on the back of the shirt. ', 'vestible', '9.95', 0, 10, 'UBN12032-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (6, 'Ubuntu Vivid Vervet 15.04 Ladies T-Shirt', 'Native to Africa, the vervet monkey is known for its most human-like characteristics which makes it a perfect nonhuman primate model for understanding genetic and social behaviors of humans. The most significant studies done on vervet monkeys involve their communication and alarm calls, specifically in regard to kin and group recognition and particular predator sightings.', 'vestible', '11.00', 0, 14, 'UBN12037-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (7, 'Ubuntu Infographic Mens T-shirt', 'A statement t-shirt to add to your collection, representing Ubuntu at its very core! With the trademark COF logo embedded in the center and the fluid UbuntuTouch infographic, this t-shirt truly represents Ubuntu to the present day. Love Ubuntu, be Ubuntu, wear Ubuntu! Made from 100% cotton and finished with the Ubuntu and Circle of Friends logo on the back of the shirt.', 'vestible', '9.95', 0, 50, 'UBN11041-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (8, 'Circle of Friends Dot Design T-shirt Mens ', 'Back by popular demand, but more vibrant and eye catching than ever before! This is the perfect t-shirt for any Ubuntu enthusiast, in our trademark Ubuntu orange and with our signature Circle of Friends dot design on the front. Made from 100% cotton and finished with the Ubuntu logo on the back of the shirt. ', 'vestible', '10.25', 0, 42, 'UBN11040-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (9, 'Ubuntu Icons T-shirt', 'Feast your eyes on the new Ubuntu Icons T-shirt, featuring the trademark Ubuntu logo and tag line on the back. Add this piece to your Ubuntu wearable collection and make a statement, that Ubuntu is \"more than just an operating system\". ', 'vestible', '10.23', 0, 48, 'UBN11033-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (10, 'Ubuntu Cap (Orange)', 'Turn heads in this iconic orange Ubuntu Logo Cap. Add this essential piece of head wear to your Ubuntu wearables collection and make a statement with the 3D embroidered \"Circle of Friends\" logo prominently situated on the front of the cap. To complete the look, the cap features an embossed Ubuntu logo on the strap adjuster and is even finished with a white \"Circle of Friends\" tag attached to the right hand side. ', 'vestible', '7.75', 0, 5, 'UBN60008-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (11, 'Ubuntu Cap (Grey)', 'Make a statement in this Ubuntu Logo Cap, a perfect fit for any Ubuntu enthusiast.\nFeaturing a 3D embroidered Ubuntu logo on the front of the cap , a \"Circle of Friends\" button on the top and an embossed logo on the adjuster of the cap, this essential piece of head wear is ideal for any occasion, and represents Ubuntu at every angle. ', 'vestible', '7.50', 0, 20, 'UBN60007-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (12, 'Circle of Friends Dot Ladies T-shirt (Aubergine)', 'Add some colour to your wardrobe with an aubergine t-shirt featuring a Circle of Friends dot design to the front, and the Ubuntu logo nestled on the nape of the shirt.', 'vestible', '10.25', 0, 39, 'UBN12014-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (13, 'Ubuntu Polo-shirt (Grey)', 'If polo-shirts are your thing, then you are going to love this bespoke design - Cool grey shirt, with orange detailing on the cuffs and collar and complete with an Ubuntu Circle of Friends label on the bottom hem of the shirt and the Ubuntu wordmark logo embroidered to the left chest. And if that\'s not enough, there is even an Ubuntu label on the inside neckline. Who can now say polo-shirts are not their thing?', 'vestible', '15.99', 0, 44, 'UBN11021-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (14, 'Ubuntu Polo-shirt (White)', 'Introducing another variation of the popular bespoke design - White polo-shirt, with orange detailing on the cuffs and collar and complete with an Ubuntu Circle of Friends label on the bottom hem of the shirt, and the Ubuntu wordmark logo embroidered to the left chest. And if that\'s not enough, there is even an Ubuntu label on the inside neckline. Who says polo-shirts can\'t be fun and stylish?', 'vestible', '15.99', 0, 46, 'UBN11027-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (15, 'Ubuntu Hoodie (Mens)', 'Keep cosy, but look cool! Made from 80% cotton and 20% polyester, this slate grey garment features fleece lining on the inside, a draw-cord hood, rib cuffs, and waistband. Completed with a fully customised subtle Ubuntu design which features an Ubuntu label on the inside neck, orange pull cords, an orange zipper pull with a dot design, a circle of friends label sewn onto left sleeve cuff, a Ubuntu label sewn onto the bottom right of the garment, and a funky dot design across the back of the hoodie.\n', 'vestible', '29.95', 0, 105, 'UBN20007-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (16, 'Ubuntu Regatta Fleece', 'Whether you want to keep warm, or simply look great, why not do so with an Ubuntu Regatta fleece jacket. Dark grey fleece, with Ubuntu logo embroidered on left chest.\n', 'vestible', '24.99', 0, 50, 'UBN20002-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (17, 'Ubuntu Pictogram Mousemat and Coaster Sets', 'Compliment your desk with a choice of two new Ubuntu mousemat and coaster sets. With this trademark pictogram mouse mat and a choice of two stunning sets of coasters you are bound to find a set personalised to you. The question is, what one will you choose?!', 'accesorio', '5.99', 0, 78, 'UBN30050-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (18, 'Ubuntu Tea Design Mug', 'Keep warm, but look cool with our new Ubuntu Mugs! Back by popular demand but with a stylish new look and in two collectible designs, these Ubuntu mugs are sure to brighten up your mood on those cold winter days. Dip dyed in our cool Ubuntu grey and available in two sleek tea and coffee designs, you are bound to find an option to tantalise your taste buds.', 'accesorio', '8.99', 0, 45, 'UBN30046-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (19, 'Ubuntu Wireless Mouse', 'Go wireless with the new and improved Ubuntu mouse. The simple, yet clean design features a discrete Ubuntu logo etched into the mouse which illuminates white when in use. If that\'s not enough, the two rechargeable power sticks included with the mouse, will make getting new batteries a thing of the past.', 'accesorio', '25.00', 0, 89, 'UBN30054-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (20, 'Ubuntu Double Sided Orange Lanyard', 'An Ubuntu lanyard is perfect for attaching identity passes, keys and the like. Features a dog-lever hook clip fitting & safety break.', 'accesorio', '1.50', 0, 4500, 'UBN30052-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (21, 'Ubuntu Coffee Design Mug', 'Keep warm, but look cool with our new Ubuntu Mugs! Back by popular demand but with a stylish new look and in two collectible designs, these Ubuntu mugs are sure to brighten up your mood on those cold winter days. Dip dyed in our cool Ubuntu grey and available in two sleek tea and coffee designs, you are bound to find an option to tantalise your taste buds.', 'accesorio', '8.99', 0, 256, 'UBN30045-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (22, 'Ubuntu Pin Badge', 'Share your love of Ubuntu and spruce up your backpacks or blazers with this smart Circle of Friends enamel lapel badge. 20mm Pin badge.', 'accesorio', '1.99', 0, 8000, 'UBN40013-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (23, 'Ubuntu Messenger Bag', 'We have teamed up with Ogio, to create a custom-designed, stylish and durable bag - perfect for the frequent traveller / commuter.', 'accesorio', '59.95', 0, 150, 'UBN50010-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (24, 'Ubuntu 4-in-1 Pen', 'Take yourself back to your youth, with this old time classic Papermate ballpoint pen. With the Ubuntu logo, creativity and flare rolled into one single pen, you can document your thoughts, organise your notes or doodle to your hearts content. You can even change colour according to your mood with the choice of a black, blue, red or purple pen. But why have one colour when you can have four?.', 'accesorio', '2.20', 0, 450, 'UBN30048-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (25, 'Ubuntu Backpack', 'We have teamed up with Ogio, to create a custom-designed, stylish and durable bag - perfect for the frequent traveller / commuter.', 'accesorio', '65.00', 0, 123, 'UBN50009-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (26, 'Ubuntu Castelli Notebook', 'The Ubuntu Castelli notebook combines practicality and luxury together. The Ubuntu orange PU leather bound notebook embossed with the Ubuntu logo, provides a contemporary twist on your traditional standard notebook. This quality driven design is reflected through every page with 240 pages of traditional lined paper, and an elasticated Ubuntu orange divider perfect for capturing and bookmarking your thoughts.', 'accesorio', '8.75', 0, 254, 'UBN30047-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (27, 'Ubuntu Stickers', 'Do you love Ubuntu and want to share it with the world? Then cover your favourite items in these nifty stickers? Featuring 12 assorted sticker designs in assorted sizes, perfect for laptops, keyboards, mice... virtually anywhere which needs some Ubuntu pizazz! Pack consists of 3 sticker sheets (32 stickers in total)', 'accesorio', '2.50', 0, 1500, 'UBN40005-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (28, 'Ubuntu Keyrings', 'Compliment your keys and never misplace them again with a choice of two beautiful, eye-catching Ubuntu keyrings. Made out of rubber and featuring an embossed 2D Circle of Friends logo on each side, completed with a subtle white \'push-to-activate\' LED light to help in those ultra-dark situations.', 'accesorio', '2.75', 0, 145, 'UBN30037-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (29, 'Ubuntu Pen', 'Rewrite history with an Ubuntu Prodir Pen, complete with a twist action retractable\nballpen. Transparent orange finish, decorated with a white Ubuntu logo on the clip.', 'accesorio', '0.85', 0, 1800, 'UBN30012-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (30, 'Ubuntu Neoprene Laptop Sleeve', 'Give your laptop the protection it deserves with a beautiful form-fitting Ubuntu laptop sleeve. Made from neoprene (grey), a plush fur inner lining (orange) and complete with two rubber Circle of Friends zips and a rubber badge with the Ubuntu logo. Available in 10\", 13\", 15\" and 17\" sizes.', 'accesorio', '19.95', 0, 1700, 'UBN30029-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (31, 'Ubuntu 14.04 LTS Desktop', 'What is Ubuntu?\nLoved by millions worldwide, Ubuntu is a secure, stylish operating system that couldn’t be easier to use. With no unnecessary trial software and clutter, it’s fast and it stays fast. It has amazing support for the web, thanks to the best, most secure and fastest browsers. And you can choose from thousands of free applications in the Ubuntu Software Centre.', 'software', '5.04', 0, 100, 'UBN00216-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (32, 'Ubuntu 14.04 LTS Server', 'What is Ubuntu Server?\nThis is the lean server and cloud version of Ubuntu, the world’s favourite free operating system. Ubuntu has been adopted as a trusted server platform by large and small organisations alike. It powers some of the world’s biggest websites, and it’s the most popular OS for cloud deployments everywhere. Whether you’re deploying a fanless home server or a fifty-thousand node rendering cluster, you’re in good company with Ubuntu. It’s easy to install, maintain and includes free security updates.', 'software', '5.04', 0, 100, 'UBN00217-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (33, 'Ubuntu 14.04 Bundle', 'Can\'t decide? Why not try them both!', 'software', '6.11', 0, 100, 'UBN00218-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (34, 'Ubuntu Utopic Unicorn 14.10 Ladies T-Shirt', 'The unicorn is a dream-like, legendary animal that has been described since antiquity as a white horse with a large, pointed, spiralling horn projecting from the centre of its forehead. Often a symbol of purity and grace, this mythical creature has been the subject of much speculation and inventiveness from people trying to prove its existence.', 'ultimo', '10.00', 2.00, 5, 'UBN12036-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (35, 'Ubuntu Utopic Unicorn 14.10 Mens T-Shirt', 'The unicorn is a dream-like, legendary animal that has been described since antiquity as a white horse with a large, pointed, spiralling horn projecting from the centre of its forehead. Often a symbol of purity and grace, this mythical creature has been the subject of much speculation and inventiveness from people trying to prove its existence.', 'ultimo', '10.00', 2.00, 3, 'UBN11046-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (36, 'Ubuntu Flexible Keyboard', 'Ever wished you could have a waterproof keyboard, that didnt catch crumbs and dust between the keys, and that you could easily take with you wherever you go? Well now you can! Introducing the Ubuntu flexible keyboard which simply rolls up and fits into a frosted zip-lock pouch. Pair this with an Ubuntu LED travel mouse, and you\'re sorted!', 'ultimo', '15.99', 1.49, 4, 'UBN30027-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (37, 'Quantal Quetzal T-shirt 12.10 Mens T-shirt', 'The Quetzal is a bird that many consider among the world\'s most beautiful, a vibrantly coloured animal that lives in the mountainous and tropical forests of Central America. Like the Quetzal colourful and striking, this vibrant navy t-shirt is guaranteed to make you stand out in a crowd.', 'ultimo', '10.25', 2.25, 7, 'UBN11035-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (38, 'Wireless Ubuntu Boombero Speakers', 'Prepare to make noise with the new Ubuntu Boombero Speakers, a stylish, sleek and compact design that competes with the traditional wireless technologies. Amplify the music from your mobile instantly by placing your phone on top of the speakers and prepare yourself for surround sound that shocks the senses.', 'ultimo', '44.99', 0, 3, 'UBN30043-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (39, 'Saucy Salamander 13.10 Ladies T-shirt', 'There are approximately 550 extant species of the Salamander family, these amphibians although characterized by their stereotypical lizard like appearance are individual creatures in their own right. Unlike the lizard species, Salamanders are fully reliant on moist and wet habitual environments, and are unique in the sense that they are actually able to regenerate and regrow limbs and body parts!', 'ultimo', '10.25', 2.25, 6, 'UBN12030-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (40, 'Trusty Tahr 14.04LTS Ladies T-shirt', 'The tahr navigates Himalayan heights, shaggily suited, sure-footed and steady. A small tourist tahr population lived on Southern Africa\'s Table Mountain, and while they\'ve made way for indigenous animals, for a long time they symbolised hardiness and fearlessness, perched as they were against the cliffs.', 'ultimo', '10.25', 2.25, 3, 'UBN12033-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (41, 'Maverick Meerkat 10.10 Ladies T-shirts', 'To celebrate the launch of the Ubuntu 10.10 (AKA Maverick Meerkat) release, we have introduced this great design! Printed onto a Continental classic fit T-shirt, which is made from 100% Combed Cotton (Interlock 240g/7.2 Oz.).', 'ultimo', '10.85', 2.85, 2, 'UBN12010-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (42, 'Quantal Quetzal T-shirt 12.10 Ladies T-shirt', 'The Quetzal is a bird that many consider among the world\'s most beautiful, a vibrantly coloured animal that lives in the mountainous and tropical forests of Central America. Like the Quetzal colourful and striking, this vibrant navy t-shirt is guaranteed to make you stand out in a crowd.', 'ultimo', '10.25', 2.25, 9, 'UBN12027-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (43, 'Lucid Lynx 10.04 Ladies T-shirts', 'Introducing the Lucid Lynx 10.04 release T-shirt for women! This Classic fit T-shirt is made from 100% Comed Cotton (Interlock 240g/7.2 Oz.). The design features a Lynx print on the front; and the Ubuntu Circle of Friends logo on the back of the left shoulder.', 'ultimo', '10.85', 2.85, 4, 'UBN12008-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (44, 'Ubuntu A5 Notebook', 'Organise your thoughts, great ideas and doodles with this unique Ubuntu designed notebook. Features a clear plastic spiral and contains a combination of 100 sheets of lined, graph, plain, and dotted page designs, separated by beautiful dividers each containing a number of Ubuntu pictograms.', 'ultimo', '6.25', 0, 20, 'UBN00167-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (45, 'Raring Ringtail 13.04 Ladies T-shirt', 'Officially known as the Ringtailed cat, the Ringtail is formally a mammal of the raccoon family and a native to North America. Known for its long black and white stripy tail, this agile creature is the new 13.04 animal and featured on the 13.04 release t-shirt (a.k.a Raring Ringtail).', 'ultimo', '10.25', 2.25, 15, 'UBN12029-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (46, 'Natty Narwhal 11.04 Mens T-shirts', 'To celebrate the launch of Ubuntu 11.04 (a.k.a Natty Narwhal), we have introduced a great t-shirt featuring a narwhal design to the front, and \'Natty Narwhal 11.04\' printed on the back. Printed onto a 100% ring-spun cotton t-shirt, and complete with an orange Circle of Friends tag sewn on the left sleeve cuff - you are sure to turn heads.', 'ultimo', '10.85', 2.85, 13, 'ubn11020-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (47, 'Ubuntu Cycling Bib-shorts', 'Due to popular demand, we are proud to introduce this super stylish Ubuntu cycling bib-shorts, made by the popular Hincapie Sportswear brand. This orange and white design compromises two large orange panels featuring the Ubuntu logo down each side of the garment. Orange panel across the back. And to add the finishing touches, an orange dot design runs down each leg, and up the back of the garment.', 'ultimo', '72.99', 7.3, 18, 'UBN20004-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (48, 'Circle of Friends Dot Mens T-shirt (Aubergine)', 'Add some colour to your wardrobe with an aubergine t-shirt featuring a Circle of Friends dot design to the front, and the Ubuntu logo nestled on the nape of the shirt.', 'ultimo', '10.25', 2.25, 17, 'UBN11023-1.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (49, 'Dot Design Ubuntu T-shirt', 'Turn heads whilst wearing one of the latest Ubuntu designs featuring an Ubuntu dot design to the front, a Circle of Friends print to the back, and an Ubuntu label sewn onto the cuff of the left sleeve for that extra bit of Ubuntu magic! Made from 100% ringspun cotton.', 'ultimo', '9.95', 1.95, 6, 'UBN11019-A.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (50, 'Launchpad Ladies T-Shirt', 'Sin descripción', 'ultimo', '10.21', 4.21, 23, 'launchpad_ladies.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (51, 'Limited Edition Jaunty Jackalope Mens T-shirt - Black', 'The suspense is over as we reveal the Limited Edition Jaunty Jackalope T-shirt! Made from 100% organic cotton, you will not only look good, but feel great too! ', 'ultimo', '13.91', 5.56, 1, 'UBN11009.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (52, 'KUbuntu Ballpoint Pen White/Blue', 'Brighten up your stationery pot today with this colourful, Bic medium point retractable pen which sports a rubber grip, black ink and the friendly KUbuntu logo on the barrel.', 'ultimo', '0.70', 0.30, 56, 'KUB30005.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (53, 'I do it with KUbuntu Ladies T-shirt', 'Show the world that you do it with KUbuntu. This T-shirt is light blue, eco-friendly and made from 100% organic cotton.', 'ultimo', '10.43', 4.18, 12, 'KUB12001.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (54, 'KUbuntu Side Logo Ladies T-shirt', 'Go green and look great in this 100% organic cotton KUbuntu T-shirt in white.', 'ultimo', '10.43', 4.18, 11, 'KUB120002.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (55, 'KUbuntu Mixed Sticker Sheets', 'Part of the new KUbuntu sticker family, this sticker sheet has been designed with variation in mind. Choose from big or small Circle of Cogs stickers to an I HEART KUbuntu design. This sticker sheet is printed onto clear vinyl with a laminate over-coating – perfect for making laptops and desktops look even cooler.', 'ultimo', '0.43', 0.18, 45, 'KUB40000.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (56, 'I do it with KUbuntu Mens T-shirt', 'Show the world that you do it with KUbuntu. This T-shirt is light blue, eco-friendly and made from 100% organic cotton.', 'ultimo', '10.43', 4.18, 2, 'KUB11002.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (57, 'Ubuntu Advantage Standard Desktop (5-pack)', 'Get your business essential coverage for general business use of Ubuntu desktop. Ubuntu Advantage Standard Desktop includes the hosted systems management service, Landscape, to more easily manage your Ubuntu desktops and keep them up to date.', 'soporte', '385.00', 0, 999, 'desktop.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (58, 'Ubuntu Advantage Advanced Desktop (5-pack)', 'Get your business the necessary coverage for intensive use of Ubuntu desktop as a workstation. Ubuntu Advantage Advanced Desktop ensures your developers are supported for complex workstation usage, such as desktop virtualisation.', 'soporte', '825.00', 0, 999, 'desktop.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (59, 'Ubuntu Advantage Essential Server', 'Get your business essential server coverage for general server usage. Ubuntu Advantage Essential Server helps you run your common workload, file, print, mail, and infrastructure servers (e.g. DHCP, DNS servers) more efficiently with lower resources requirements.', 'soporte', '195.00', 0, 999, 'server.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (60, 'Ubuntu Advantage Standard Server', 'Ubuntu Advantage Standard Server lets you use Ubuntu Server Edition in your enterprise with peace of mind. It gives you IP indemnification so you can deploy Open Source technology without complicated legal concerns.', 'soporte', '427.00', 0, 999, 'server.jpg');
INSERT INTO `TIENDAONLINE`.`PRODUCTOS` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCCION_PRODUCTO`, `CATEGORIA_PRODUCTO`, `PRECIO_PRODUCTO`, `DESCUENTO`, `STOCK`, `FOTO`) VALUES (61, 'Ubuntu Advantage Advanced Server', 'Get total coverage for your business-critical Ubuntu servers. Ubuntu Advantage Advanced Server gives you 24x7 phone and online access to enterprise expertise.', 'soporte', '733.01', 0, 999, 'server.jpg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TIENDAONLINE`.`USUARIOS`
-- -----------------------------------------------------
START TRANSACTION;
USE `TIENDAONLINE`;
INSERT INTO `TIENDAONLINE`.`USUARIOS` (`ID`, `USER`, `PASSWORD`, `EMAIL`, `DIRECCION`, `CIUDAD`, `PROVINCIA`, `CP`, `PAIS`, `telefono`, `ULTIMA_CONEC`, `NIVEL_PRIVILEGIO`) VALUES (DEFAULT, 'admin', 'admin', 'santiago.hoyos93@gmail.com', 'Calle PAdre Manjon 2, Valladolid, España', 'Valladolid', 'Valladolid', '47013', 'España', '652699539', '2016-01-25', 'admin');
INSERT INTO `TIENDAONLINE`.`USUARIOS` (`ID`, `USER`, `PASSWORD`, `EMAIL`, `DIRECCION`, `CIUDAD`, `PROVINCIA`, `CP`, `PAIS`, `telefono`, `ULTIMA_CONEC`, `NIVEL_PRIVILEGIO`) VALUES (DEFAULT, 'usuario2', 'Password2', 'correo2@gregoriofer.com', 'Calle del Gabilondo 2, Valladolid', 'Valladolid', 'Valladolid', '47002', 'España', '652699539', '2016-01-01', 'cliente');
INSERT INTO `TIENDAONLINE`.`USUARIOS` (`ID`, `USER`, `PASSWORD`, `EMAIL`, `DIRECCION`, `CIUDAD`, `PROVINCIA`, `CP`, `PAIS`, `telefono`, `ULTIMA_CONEC`, `NIVEL_PRIVILEGIO`) VALUES (DEFAULT, 'usuario3', 'Password3', 'correo3@gregoriofer.com', 'Calle del gabilondo 3, Valldolid', 'Valladolid', 'Valladolid', '47003', 'España', '652699539', '2016-01-03', 'cliente');
INSERT INTO `TIENDAONLINE`.`USUARIOS` (`ID`, `USER`, `PASSWORD`, `EMAIL`, `DIRECCION`, `CIUDAD`, `PROVINCIA`, `CP`, `PAIS`, `telefono`, `ULTIMA_CONEC`, `NIVEL_PRIVILEGIO`) VALUES (DEFAULT, 'usuario4', 'Password4', 'correo4@gregoriofer.com', 'Calle del gabilondo 4, Valldolid', 'Valladolid', 'Valladolid', '47004', 'España', '652699539', '2005-01-04', 'cliente');
INSERT INTO `TIENDAONLINE`.`USUARIOS` (`ID`, `USER`, `PASSWORD`, `EMAIL`, `DIRECCION`, `CIUDAD`, `PROVINCIA`, `CP`, `PAIS`, `telefono`, `ULTIMA_CONEC`, `NIVEL_PRIVILEGIO`) VALUES (DEFAULT, 'usuario5', 'Password5', 'correo5@gregoriofer.com', 'Calle del gabilondo 5, Valladolid', 'Valladolid', 'Valladolid', '47005', 'España', '652699539', '2007-01-05', 'cliente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TIENDAONLINE`.`COMPRAS`
-- -----------------------------------------------------
START TRANSACTION;
USE `TIENDAONLINE`;
INSERT INTO `TIENDAONLINE`.`COMPRAS` (`ID_COMPRA`, `COMENTARIO_COMPRA`, `FK_ID_CLIENTE`) VALUES (DEFAULT, 'Primera compra', 2);
INSERT INTO `TIENDAONLINE`.`COMPRAS` (`ID_COMPRA`, `COMENTARIO_COMPRA`, `FK_ID_CLIENTE`) VALUES (DEFAULT, 'Segunda Compra', 3);
INSERT INTO `TIENDAONLINE`.`COMPRAS` (`ID_COMPRA`, `COMENTARIO_COMPRA`, `FK_ID_CLIENTE`) VALUES (DEFAULT, 'Tercera compra', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TIENDAONLINE`.`LINEAS_COMPRA`
-- -----------------------------------------------------
START TRANSACTION;
USE `TIENDAONLINE`;
INSERT INTO `TIENDAONLINE`.`LINEAS_COMPRA` (`CANTIDAD`, `FK_ID_COMPRA`, `FK_ID_PRODUCTO`) VALUES (5, 1, 1);
INSERT INTO `TIENDAONLINE`.`LINEAS_COMPRA` (`CANTIDAD`, `FK_ID_COMPRA`, `FK_ID_PRODUCTO`) VALUES (8, 2, 15);
INSERT INTO `TIENDAONLINE`.`LINEAS_COMPRA` (`CANTIDAD`, `FK_ID_COMPRA`, `FK_ID_PRODUCTO`) VALUES (7, 3, 4);
INSERT INTO `TIENDAONLINE`.`LINEAS_COMPRA` (`CANTIDAD`, `FK_ID_COMPRA`, `FK_ID_PRODUCTO`) VALUES (5, 1, 7);
INSERT INTO `TIENDAONLINE`.`LINEAS_COMPRA` (`CANTIDAD`, `FK_ID_COMPRA`, `FK_ID_PRODUCTO`) VALUES (8, 2, 10);

COMMIT;

